### ISSUE TITLE
Link to model weights on OneDrive is broken

### ISSUE THREAD

**Issue by jsguen** [zcablii/SARDet_100K#23]
Hi,
I want to try out your pre-trained models, but the download link for the weights on OneDrive is not working, and I do not have access to Baidu.
Can you look into the problems with OneDrive?
Thank you in advance

**Comment by zcablii** [comment]
Thank you for bringing this to my attention. The issue with the OneDrive link occurred because my personal OneDrive storage reached its limit, and I accidentally cleaned up the shared folder. I have updated the link in README, but please note that the weights are quite large and might still be uploading.
