### ISSUE TITLE
There may be some annotation errors

### ISSUE THREAD

**Issue by NeverWangX** [zcablii/SARDet_100K#3]
There are some target annotations with an area of 0 in the annotation file, such as:
{
“area": 0,
"iscrowd": 0,
"image_id": 6914,
"bbox": [191.0, 1.0, 47.0, 0.0],
"category_id": 0,
"id": 18603,
"ignore": 0,
"segmentation": []
}
Do you need to clear these annotations with an area of 0

**Comment by zcablii** [comment]
Thank you for bringing this to our attention! The instances of zero area annotations are a result of the image splitting process. However, these do not impact the training of models because, by default, we filter out instances with areas smaller than 16 pixels in the dataloader config files. This threshold was set specifically to address situations where instances may tear apart during the image splitting process, with zero area instances being a particular case of this scenario. Feel free to safely remove such cases if you prefer, but rest assured, they won't negatively affect the model's training.
